### PR TITLE
fix(angular): Disabled submit button when API call status is pending.

### LINKED ISSUE #2092: Angular Authenticator doesn't disable button when sign in is pending
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

Angular

### Which UI component?

Authenticator

### How is your app built?

Angular CLI

### Please describe your bug.

Angular Authenticator does not disable the sign in submit button after it's been clicked. 

React in contrary disables the button, grays out the button, and then puts a loading spinner whenever it's clicked.

### What's the expected behaviour?

For it to replicate React behavior.

### Help us reproduce the bug!

1. clone amplify-ui repo
2. run angular-examples sample app
3. Open app and go to http://localhost:3000/ui/components/authenticator/sign-up-with-email
5. Try signing in, you'll see the button is not disabled

### Code Snippet

Here's where the sign in button is:

https://github.com/aws-amplify/amplify-ui/blob/736cfe7cb3544bf0ecae5ab2c3b2caf381b497c4/packages/angular/projects/ui-angular/src/lib/components/authenticator/components/sign-in/sign-in.component.html#L25-L32

Here's where the button primitive declaration is at: https://github.com/aws-amplify/amplify-ui/blob/736cfe7cb3544bf0ecae5ab2c3b2caf381b497c4/packages/angular/projects/ui-angular/src/lib/primitives/button/button.component.ts#L7-L12

Here are the recommended steps to fix this:

1.  Add new `@Input()`s `isDisabled` and `isLoading`  to the button primitive
2. Whenever `isDisabled` or `isLoading` is true, add appropriate className for CSS to take effect. [This](https://github.com/aws-amplify/amplify-ui/blob/736cfe7cb3544bf0ecae5ab2c3b2caf381b497c4/packages/react/src/primitives/Button/Button.tsx#L30-L36) is how React does it. For example, if `isDisabled` is true, then you'll add `amplify-button--disabled` classname. Adding this classname will _automatically_ add desired disabled style to the button, so you don't have to make any css changes.
3.  Set `isDisabled` and `isLoading` props to true in sign in component whenever sign in is in progress. To do so, use [Authenticator Service](https://ui.docs.amplify.aws/angular/components/authenticator#authenticator-service) that is already in the `sign-in` component:

https://github.com/aws-amplify/amplify-ui/blob/736cfe7cb3544bf0ecae5ab2c3b2caf381b497c4/packages/angular/projects/ui-angular/src/lib/components/authenticator/components/sign-in/sign-in.component.ts#L32

In your `sign-in.component.html`, you would do

```diff
  <button
    amplify-button
    fontWeight="normal"
    size="small"
    variation="link"
    fullWidth="true"
+   [isDisabled]="authenticator.isPending"
+   [isLoading]="authenticator.isPending"
    (click)="authenticator.toResetPassword()"
  >
```

### Additional information and screenshots

_No response_

### PR DESCRIPTION
**Pull request by SantoshLatpate**
#### Description of changes

Changes to Angular Component for  Authenticator doesn't disable button when submit call is pending.

#### Issue #, if available

fixes #2092

#### Description of how you validated changes

 Button are not disabled in authentication flow
https://user-images.githubusercontent.com/30000896/174901010-02efbc05-3b3a-4be2-8d06-6b4026c98e86.mp4

Now button are disabled in authentication flow
https://user-images.githubusercontent.com/30000896/174901814-09fb5e45-c3d2-44a1-8da6-8865d2696231.mp4

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are updated
- [ ] No side effects or [`sideEffects`](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/CONTRIBUTING.md#code-standards) field updated
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by reesscot** [comment]
@wlee221 @SantoshLatpate Is there an issue we can link to for this?

**Comment by reesscot** [comment]
@SantoshLatpate Please provide before and after GIFs demonstrating the issue.

File: packages/angular/projects/ui-angular/src/lib/primitives/button/button.component.ts [hunk 1]
```diff
@@ -28,6 +29,10 @@ export class ButtonComponent implements OnInit {
     if (this.fullWidth) {
       className += ` amplify-button--fullwidth`;
     }
+    if (this.disabled) {
```
Comment (zchenwei) [inline packages/angular/projects/ui-angular/src/lib/primitives/button/button.component.ts:32]: I could be wrong but why not use `classnames`(https://www.npmjs.com/package/classnames) to get rid of those `if` conditions?

**Comment by wlee221** [comment]
Looking good! Few things to add to this PR:

- a descriptive PR title
- it should follow conventional commit: https://www.conventionalcommits.org/en/v1.0.0/
  - e.g. it should start with fix(angular): your title
- Link to the original issue (#2092)
- Add GIFs if you can, I use [kap](https://getkap.co/) (make sure you don't record sensitive info!)

File: packages/angular/projects/ui-angular/src/lib/primitives/button/button.component.ts (hunk 1 above)
Comment (wlee221) [reply packages/angular/projects/ui-angular/src/lib/primitives/button/button.component.ts:32]: Ooh, we've never seen that package before tbh. What do you think @SantoshLatpate? 

Doesn't have to be this PR, but looks like it can simplify our code a little.

File: packages/angular/projects/ui-angular/src/lib/primitives/button/button.component.ts [hunk 2]
```diff
@@ -7,6 +7,7 @@ import { Component, HostBinding, Input, OnInit } from '@angular/core';
 export class ButtonComponent implements OnInit {
   @Input() type: 'submit' | 'button' = 'button';
   @Input() fullWidth: boolean | string = false;
+  @Input() disabled: boolean | string = false;
```
Comment (wlee221) [inline packages/angular/projects/ui-angular/src/lib/primitives/button/button.component.ts:10]: To match our naming conventions with React counterparts, let's name this to `isDisabled`. https://ui.docs.amplify.aws/react/components/button

File: packages/angular/projects/ui-angular/src/lib/primitives/button/button.component.ts (hunk 1 above)
Comment (SantoshLatpate) [reply packages/angular/projects/ui-angular/src/lib/primitives/button/button.component.ts:32]: I will look into classnames and if possible try to get rid of those if conditions

**Comment by SantoshLatpate** [comment]
> @wlee221 @SantoshLatpate Is there an issue we can link to for this?

**Review by wlee221 — CHANGES_REQUESTED** [review]
lgtm, my only blocker is https://github.com/aws-amplify/amplify-ui/pull/2159#discussion_r902058271.

File: packages/angular/projects/ui-angular/src/lib/primitives/button/button.component.ts (hunk 2 above)
Comment (SantoshLatpate) [reply packages/angular/projects/ui-angular/src/lib/primitives/button/button.component.ts]: Done with this changes.

File: packages/angular/projects/ui-angular/src/lib/primitives/button/button.component.ts [hunk 3]
```diff
@@ -28,6 +29,10 @@ export class ButtonComponent implements OnInit {
     if (this.fullWidth) {
       className += ` amplify-button--fullwidth`;
     }
+    if (this.isDisabled) {
+      className += ` amplify-button--disabled amplify-button--loading`;
+    }
```
Comment (wlee221) [inline packages/angular/projects/ui-angular/src/lib/primitives/button/button.component.ts:34]: Doesn't have to be this PR, but I think it'd make sense to create `isLoading` `@Input` as well when we build primitives. Authenticator doesn't use it, but others might.

File: packages/angular/projects/ui-angular/src/lib/primitives/button/button.component.ts [hunk 4]
```diff
@@ -7,6 +7,7 @@ import { Component, HostBinding, Input, OnInit } from '@angular/core';
 export class ButtonComponent implements OnInit {
   @Input() type: 'submit' | 'button' = 'button';
   @Input() fullWidth: boolean | string = false;
+  @Input() isDisabled: boolean | string = false;
```
Comment (wlee221) [inline packages/angular/projects/ui-angular/src/lib/primitives/button/button.component.ts:10]: Also doesn't have to be on this PR, but we should have types be just `boolean` instead of `boolean | string`.

**Review by wlee221 — DISMISSED** [review]
Looks good, I just noted some future improvements but nothing blocking.

**Review by ErikCH — DISMISSED** [review]
LGTM

**Review by wlee221 — DISMISSED** [review]

File: packages/angular/projects/ui-angular/src/lib/primitives/button/button.component.ts [hunk 5]
```diff
@@ -17,6 +18,10 @@ export class ButtonComponent implements OnInit {
   @HostBinding('attr.data-variation') variationAttr: string;
   @HostBinding('style.font-weight') fontWeightAttr: string;
 
+  @HostBinding('attr.disabled') get getDisabled() {
+    return this.isDisabled ? true : null;
```
Comment (wlee221) [inline packages/angular/projects/ui-angular/src/lib/primitives/button/button.component.ts:22]: Last nit, let's have this equal to `''` on happy case so that html looks like this

```
<button disabled>...</button>
```

instead of 

```
<button disabled="true"></button>
```

Comment (wlee221) [reply packages/angular/projects/ui-angular/src/lib/primitives/button/button.component.ts:22]:
```suggestion
    return this.isDisabled ? '' : null;
```

**Review by wlee221 — APPROVED** [review]

**Review by ErikCH — APPROVED** [review]
👍
