### PR TITLE
fix(authenticator): remove order keys from formFields after sorting

### LINKED ISSUE #3281: Authenticator FormFields `order` broken in 4.x
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

N/A

### What browsers are you seeing the problem on?

Chrome, Firefox, Microsoft Edge, Safari

### Please describe your bug.

When adding a custom form field to the Authenticator and specifying a custom order using formFields API, the order is incorrect as of v4 of the UI library:

Working order in v3:
https://codesandbox.io/s/authenticator-signup-order-forked-cw78g4

Broken order in v4:
https://codesandbox.io/s/authenticator-signup-order-forked-3h6du9?file=/src/App.js

### What's the expected behaviour?

The Checkbox fields and all error messages should be shown at the bottom of the page.

### Help us reproduce the bug!

See above

### Code Snippet

```typescript
// Put your code below this line.

```

### Additional information and screenshots

_No response_

### PR DESCRIPTION
**Pull request by calebpollman**
#### Description of changes
Remove `order` value from `formFields` after sorting to prevent passing it to `TextField` components

#### Issue #, if available
Fixes #3281 

#### Description of how you validated changes
Manually tested React, Angular, Vue and React Native example apps. Added unit test
#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are updated
- [x] No side effects or [`sideEffects`](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/CONTRIBUTING.md#code-standards) field updated
- [x] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by dbanksdesign — DISMISSED** [review]
LGTM! Thanks for the quick action on this!

File: packages/ui/src/helpers/authenticator/formFields/formFields.ts [hunk 1]
```diff
@@ -35,11 +35,18 @@ export const getFormFields = (
   return formFields;
 };
 
+export const removeOrderKeys = (formFields: FormFieldsArray): FormFieldsArray =>
+  formFields.map((field) => {
+    const key = field[0];
+    const values = { ...field[1], order: undefined };
```
Comment (reesscot) [inline packages/ui/src/helpers/authenticator/formFields/formFields.ts:41]: Should we add a comment for why we are doing this?
```suggestion
    const values = { ...field[1], order: undefined }; // Drop order key to prevent passing to form field UI components 
```

**Review by wlee221 — APPROVED** [review]

File: packages/ui/src/helpers/authenticator/formFields/formFields.ts (hunk 1 above)
Comment (calebpollman) [reply packages/ui/src/helpers/authenticator/formFields/formFields.ts:41]:
```suggestion
    // Drop order key to prevent passing to form field UI components
    const values = { ...field[1], order: undefined };
```

**Review by reesscot — APPROVED** [review]

**Review by wlee221 — APPROVED** [review]

**Review by ErikCH — APPROVED** [review]
I just looked at the Vue implementation, and it should be OK either way. We never spread the props like we do in React, so the order key is never added to the form fields.

**Review by sreeramsama — APPROVED** [review]
