### PR TITLE
fix(style): adjust switch track color to comply with 3:1 contrast ratio

### LINKED ISSUE #1820: Bug: SwitchField doesn't meet WCAG AA minimum contrast ratio
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

N/A

### Please describe your bug.

SwitchField doesn't meet minimum WCAG AA for User Interface Components
Screen Shot 2022-05-03 at 4 45 14 PM

Current track background color is #8E939F and contrast when in off state is 1.14:1 and should be a minimum of 3:1.
Screen Shot 2022-05-03 at 4 53 59 PM
https://webaim.org/resources/contrastchecker/

It looks like we need to add a neutral 70 color between the 60 and 80. I tried `--amplify-color-neutral-60` and it was too light. `--amplify-color-neutral-80` works but it seem visually too contrasty. @dbanksdesign do you have an objection to adding a level 70? I know it breaks from the pattern of the other color ranges.
```
    60: { value: 'hsl(210, 6%, 70%)' },
    80: { value: 'hsl(210, 10%, 40%)' },
```

### What's the expected behaviour?

Should meet WCAG contrast standards.

### Help us reproduce the bug!

Visit the docs:
https://ui.docs.amplify.aws/components/switchfield
Switch to Light mode
Notice that the switch color doesn't have much contrast.

### Code Snippet

```typescript
// Put your code below this line.

```

### Additional information and screenshots

_No response_

### PR DESCRIPTION
**Pull request by zchenwei**
#### Description of changes

1. Bump up neutral-60 to 3:1 ratio compared with white

2. Update track background color of switch and slider to use neutral-60

#### Issue #, if available

Fixes #1820 

#### Description of how you validated changes

| Light   | Dark |
| ----------- | ----------- |
| Screen Shot 2022-05-11 at 2 49 55 PM | Screen Shot 2022-05-11 at 2 51 40 PM  |
| Screen Shot 2022-05-11 at 3 02 07 PM | Screen Shot 2022-05-11 at 3 28 09 PM |

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are updated
- [x] No side effects or [`sideEffects`](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/CONTRIBUTING.md#code-standards) field updated

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: docs/src/pages/components/switchfield/examples/SwitchFieldThumbColorExample.tsx [hunk 1]
```diff
@@ -5,7 +5,7 @@ export const SwitchFieldThumbColorExample = () => {
   return (
     <SwitchField
       label="This is a switch"
-      thumbColor={`${tokens.colors.red[60]}`}
+      thumbColor={`${tokens.colors.orange[10]}`}
```
Comment (zchenwei) [inline docs/src/pages/components/switchfield/examples/SwitchFieldThumbColorExample.tsx:8]: This color make sure 3:1 contrast ratio in both light and dark mode

**Review by reesscot — APPROVED** [review]

File: docs/src/pages/components/switchfield/examples/SwitchFieldThumbColorExample.tsx (hunk 1 above)
Comment (dbanksdesign) [reply docs/src/pages/components/switchfield/examples/SwitchFieldThumbColorExample.tsx:8]: Could we make this un stringified? This line could be simplified to `thumbColor={tokens.colors.orange[10]}`

**Review by dbanksdesign — APPROVED** [review]
LGTM! Just one comment not really relating to your change
