### PR TITLE
fix(authenticator): explicitly filter special characters allowed by Cognito

### LINKED ISSUE #2052: Underscore _ not being validated as a special character on Authenticator
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Next.js

### Please describe your bug.

The <Authenticator /> component isn't recognizing the underscore '_' as a special character when signing up a new account into Cognito.

When I add a test e-mail with a test password like 'Test_123' with the requirements of more than 8 characters, uppercase, lowercase and special character I get an error even though the password has all the requirements. I see that this only happens with the underscore. Because if I just add a dot '.' or other special character in the password then it validates it correctly.

### What's the expected behaviour?

To get the underscore as a valid special character.

### Help us reproduce the bug!

Try to sign up a new user with the mentioned password rules, and the underscore won't be accepted as one.

### Code Snippet

_No response_

### Additional information and screenshots

_No response_

### PR DESCRIPTION
**Pull request by wlee221**
#### Description of changes

Previously in our password validation util, we were matching special characters with `\W`, which matches all non-word character **except underscore**. 

https://github.com/aws-amplify/amplify-ui/blob/5b713ad3f5ddaf24583f7589138c1545a26f6c3a/packages/ui/src/machines/authenticator/defaultServices.ts#L109

This was not sufficient because underscore is a valid special character. Instead, this PR makes password rules more explicit by directly matching [special characters allowed by Cognito](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-policies.html). 

#### Issue #, if available

Fixes #2052

#### Description of how you validated changes

New unit test

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are updated
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by 0618 — APPROVED** [review]

File: packages/ui/src/machines/authenticator/defaultServices.ts [hunk 1]
```diff
@@ -106,7 +106,7 @@ export const defaultServices = {
             password_complexity.push('Password must have numbers');
           break;
         case 'REQUIRES_SYMBOLS':
-          if (!/[\W]/.test(password))
+          if (!/[\^$*.[\]{}()?"!@#%&\/\\,><':;|_~`=+\-\ ]/.test(password))
```
Comment (wlee221) [inline packages/ui/src/machines/authenticator/defaultServices.ts:109]:
```suggestion
          // https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-policies.html
          if (!/[\^$*.[\]{}()?"!@#%&\/\\,><':;|_~`=+\-\ ]/.test(password))
```

File: packages/ui/src/machines/authenticator/__tests__/defaultService.test.ts [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+  it('happy case with valid password and strict password policy', async () => {
+    const password = 'UnitTest_Password1';
+    const result = await validateFormPassword({ password }, touched, {
+      passwordPolicyCharacters: ['REQUIRES_SYMBOLS'],
+      passwordPolicyMinLength: 1,
+    });
+    expect(result).toBe(null);
+  });
+
+  it('unhappy cases with invalid passwords and strict password policy', async () => {
```
Comment (calebpollman) [inline packages/ui/src/machines/authenticator/__tests__/defaultService.test.ts:35]: Can we break this up in to three separate tests? Unless the results of a second test rely on the output of the first, tend to avoid grouping tests

File: packages/ui/src/machines/authenticator/__tests__/defaultService.test.ts [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+      password: [
+        'Password must have at least 8 characters',
+        'Password must have numbers',
+        'Password must have upper case letters',
+        'Password must have special characters',
+      ],
+    });
+  });
+
+  it('happy case with valid password and lenient password policy', async () => {
```
Comment (calebpollman) [inline packages/ui/src/machines/authenticator/__tests__/defaultService.test.ts:75]: Nit: use names that read starting with `it`, example
```
it('validates as expected with valid password and lenient password policy')
```

File: packages/ui/src/machines/authenticator/defaultServices.ts [hunk 4]
```diff
@@ -106,7 +106,8 @@ export const defaultServices = {
             password_complexity.push('Password must have numbers');
           break;
         case 'REQUIRES_SYMBOLS':
-          if (!/[\W]/.test(password))
+          // https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-policies.html
```
Comment (calebpollman) [inline packages/ui/src/machines/authenticator/defaultServices.ts:109]: 👍

**Review by calebpollman — COMMENTED** [review]
LGTM, thanks for adding the unit tests! just some minor feedback, let me know your thoughts

File: packages/ui/src/machines/authenticator/__tests__/defaultService.test.ts (hunk 3 above)
Comment (wlee221) [reply packages/ui/src/machines/authenticator/__tests__/defaultService.test.ts:75]: Oh gosh, I finally realize what `it` stands for.

Comment (wlee221) [reply packages/ui/src/machines/authenticator/__tests__/defaultService.test.ts:79]: [1336cb0](https://github.com/aws-amplify/amplify-ui/pull/2071/commits/1336cb0747003cd4167359498ae19c5937da5458)

File: packages/ui/src/machines/authenticator/__tests__/defaultService.test.ts (hunk 2 above)
Comment (wlee221) [reply packages/ui/src/machines/authenticator/__tests__/defaultService.test.ts]: [1336cb0](https://github.com/aws-amplify/amplify-ui/pull/2071/commits/1336cb0747003cd4167359498ae19c5937da5458)

**Review by calebpollman — APPROVED** [review]
🚢

File: packages/ui/src/machines/authenticator/__tests__/defaultService.test.ts (hunk 3 above)
Comment (wlee221) [reply packages/ui/src/machines/authenticator/__tests__/defaultService.test.ts]: I made few more wording commits after [1336cb0](https://github.com/aws-amplify/amplify-ui/pull/2071/commits/1336cb0747003cd4167359498ae19c5937da5458)... I keep missing one by one!

I think it looks good now, will merge later today if no objections.
