### PR TITLE
fix: export Korean tranlsations to the right key(ko)

### LINKED ISSUE #3552: could you please change the Internationalization (I18n) for Korean, 'kr' to 'ko'   (The Authenticator ships with translations)
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React, Other

### Which UI component?

Authenticator

### How is your app built?

Create React App, Amplify UI primitive

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

Internationalization (I18n)
The Authenticator ships with [translations] (https://github.com/aws-amplify/amplify-ui/blob/main/packages/ui/src/i18n/translations.ts) for:

**kr – Korean**

**Even the "ClientDevice from aws-amplify ", It show Korean as 'ko'**

Please consider it to change to 'ko'.  Thank you. 

### What's the expected behaviour?

var clientDevice = ClientDevice.clientInfo()
console.log ( 'language set:  ', clientDevice.language)
I hope this show 'ko' not 'kr'

So, if the Authenticator ships with [translations] (https://github.com/aws-amplify/amplify-ui/blob/main/packages/ui/src/i18n/translations.ts) for:

**ko – Korean**

It should be better. cause it may not need to write reform to 'ko' to 'kr' by any coder. 

### Code Snippet

```typescript
// Put your code below this line.
import '@aws-amplify/ui-react/styles.css'
import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './components/App';
import { Amplify, I18n, ClientDevice } from 'aws-amplify';
import { Authenticator, translations } from '@aws-amplify/ui-react';
import awsconfig from './aws-exports'
Amplify.configure(awsconfig)

/* language ? */
I18n.putVocabularies(translations);
var clientDevice = ClientDevice.clientInfo()
if (clientDevice.language === 'ko' || clientDevice.language === 'kr') {
   console.log("user's language:", clientDevice.language)
   I18n.setLanguage('kr');
} else {
   I18n.setLanguage(clientDevice.language);
}
// --------------

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
   <React.StrictMode>
      <Authenticator >
         <App />
      </Authenticator>
   </React.StrictMode >
);
```

### Additional information and screenshots

_No response_

### PR DESCRIPTION
**Pull request by zchenwei**
#### Description of changes

export Korean translations to `ko` key

#### Issue #, if available

fixes #3552 

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] No side effects or [`sideEffects`](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/CONTRIBUTING.md#code-standards) field updated
- [x] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by ioanabrooks — APPROVED** [review]

**Review by wlee221 — APPROVED** [review]

File: packages/ui/src/i18n/translations.ts [hunk 1]
```diff
@@ -85,7 +85,9 @@ export const translations: Record<string, Dict> = {
   id: idDict,
   it: itDict,
   ja: jaDict,
+  // TODO: remove kr in next major release
```
Comment (reesscot) [inline packages/ui/src/i18n/translations.ts:88]: Can you please add a ticket in the Major Release project for this?

**Review by reesscot — APPROVED** [review]

File: packages/ui/src/i18n/translations.ts (hunk 1 above)
Comment (zchenwei) [reply packages/ui/src/i18n/translations.ts:88]: Done
