### PR TITLE
fix(authenticator): hide Resend Code button during password-based MFA

### LINKED ISSUE #6954: Resend Code on SignIn doesn't resend the code
### Before creating a new issue, please confirm:

- [x] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [x] I have tried disabling all browser extensions or using a different browser
- [x] I have tried deleting the node_modules folder and reinstalling my dependencies
- [x] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Vite

### What browsers are you seeing the problem on?

_No response_

### Which region are you seeing the problem in?

_No response_

### Please describe your bug.

When a user has their MFA enabled (lets say SMS), and they perform a sign-in, they get the view of entering the OTP, and there is a "Resend Code" button being rendered (All by the Authenticator component).

However, as I understand from AWS Support, resending the code during sign-in is not actually supported, and user is expected to go via initAuth again. (When I click the Resend Code I get an error `password is required to signIn`).

Am I missing anything?
I mean, Amplify UI renders this button for a reason, right?
What is the quickest workaround to have this button re-init the auth flow, either programmatically, or by redirecting the user back to entering email+password?

Also, is there an ETA for implementing this ability?
Thanks

### What's the expected behaviour?

Resend Code during sign-in should, in face, resend the OTP code

### Help us reproduce the bug!

1. Have a user with MFA set (like SMS)
2. Sign in
3. Click Resend Code button
4. `password is required to signIn` is shown, and no new code is sent

### Code Snippet

```typescript
// Put your code below this line.

```

### Console log output

_No response_

### Additional information and screenshots

"@aws-amplify/ui-react": "^6.15.3"
"aws-amplify": "^6.16.3"

### PR DESCRIPTION
**Pull request by osama-rizk**
Description of changes

   The "Resend Code" button was incorrectly displayed during password-based MFA sign-in (e.g., SMSMFA, EMAILOTP
   challenges triggered after a traditional password sign-in). Clicking it resulted in the error password is
   required to signIn because the underlying resendSignInCode service attempts to re-initiate sign-in via
   USER_AUTH flow without a password.

   This PR updates ConfirmSignInFooter to only show the "Resend Code" button when the sign-in was initiated via a
   passwordless (USER_AUTH) flow (e.g., EMAIL_OTP, SMS_OTP, WEB_AUTHN). The button is now hidden when
   availableAuthMethods only contains PASSWORD, which indicates a traditional password-based sign-in.

   Changes:

   - ConfirmSignInFooter.tsx: Added selectedAuthMethod and availableAuthMethods to the useAuthenticator selector.
   The showResendCode condition now checks that a non-password auth method exists before rendering the button.

   Issue #, if available

   Fixes #6954

   Description of how you validated changes

   - Reproduced the bug using a Vite + React app with SMS MFA enabled (password-based sign-in)
   - Verified the "Resend Code" button no longer appears during password-based MFA sign-in
   - Confirmed the button still appears correctly during passwordless (USER_AUTH) sign-in flows

   Checklist

   - [x] Have read the Pull Request Guidelines
   - [x] PR description included
   - [ ] yarn test passes and tests are updated/added
   - [x] PR title and commit messages follow conventional commit
   (https://www.conventionalcommits.org/en/v1.0.0/#summary) syntax
   - [ ] If this change should result in a version bump, changeset added
   (https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md) (This can be done after
   creating the PR.) This does not apply to changes made to docs, e2e, examples, or other private packages.

   By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0
   license.

### CODE REVIEW

File: packages/react/src/components/Authenticator/shared/ConfirmSignInFooter.tsx [hunk 1]
```diff
@@ -14,16 +14,29 @@ const {
...
+    context.resendCode,
+    context.selectedAuthMethod,
+    context.availableAuthMethods,
+  ]);
 
-  const showResendCode = isOtpChallenge(challengeName) && resendCode;
+  // Only show "Resend Code" for passwordless (USER_AUTH) flows.
+  // Password-based sign-in does not support resending MFA codes.
+  const hasPasswordlessMethod =
+    !!selectedAuthMethod ||
```
Comment (soberm) [inline packages/react/src/components/Authenticator/shared/ConfirmSignInFooter.tsx:36]: This is always true.

Comment (soberm) [reply packages/react/src/components/Authenticator/shared/ConfirmSignInFooter.tsx:36]: Should probably be

```
const hasPasswordlessMethod =
  (!!selectedAuthMethod && selectedAuthMethod !== 'PASSWORD') ||
  !!availableAuthMethods?.some((m) => m !== 'PASSWORD');
```

Comment (osama-rizk) [reply packages/react/src/components/Authenticator/shared/ConfirmSignInFooter.tsx]: Done.

**Review by soberm — APPROVED** [review]

**Review by bobbor — APPROVED** [review]
