### PR TITLE
fix: Fix docs error messages for Authenticator demo

### LINKED ISSUE #2066: Docs: Error message appearing on authenticator in docs site.
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Docs Site

### Please describe your bug.

The Authenticator documentation (https://ui.docs.amplify.aws/react/components/authenticator#social-providers) will display an error message when interacting with it.

Screen Shot 2022-06-09 at 11 57 26 AM

### What's the expected behaviour?

No error message should be displayed

### Help us reproduce the bug!

Go to https://ui.docs.amplify.aws/react/components/authenticator#social-providers then click on 2 of the social sign in buttons.

### Code Snippet

```typescript
// Put your code below this line.

```

### Additional information and screenshots

As commented by @dbanksdesign this isn't entirely unexpected because the documentation is using the live authenticator component but there is no backend set up, however this experience could be improved by using a mock.

### PR DESCRIPTION
**Pull request by ErikCH**
#### Description of changes
Fix docs error messages when people click buttons in the authenticator in the docs.

image

image

Also fixed broken translation accordion.

Before:

image

After:

image

#### Issue #, if available

Fixes #2066  

#### Description of how you validated changes
Manually tested

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are updated
- [x] No side effects or [`sideEffects`](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/CONTRIBUTING.md#code-standards) field updated
- [x] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: docs/src/pages/[platform]/components/authenticator/customization/LabelsAndTextDemo.tsx [hunk 1]
```diff
@@ -67,37 +62,19 @@ function Screen({ Component }: ScreenProps) {
...
-      <OnMachineInit>
-        <View data-amplify-authenticator="">
-          <View data-amplify-container="">
-            <View data-amplify-body>
-              <Screen Component={Component} />
-            </View>
+      <View data-amplify-authenticator="">
+        <View data-amplify-container="">
+          <View data-amplify-body>
+            <Screen Component={Component} />
```
Comment (ErikCH) [inline docs/src/pages/[platform]/components/authenticator/customization/LabelsAndTextDemo.tsx:74]: This used to accept a `Authenticator.<someComponent>`. However, since our refactor we've updated the `Authenticator.tsx` file and now *almost* all components require a `CustomeComponentsContext.Provider` hook. Which is not normally exported outside of the internal React implementation.

Instead, I'm using the built-in `initialState` props for the `Authenticator`, which is closer to what an actual user would use.

The limitation of this is that we no longer will be able to show the `Authenticator.SetupTOTP` example page. I feel like this is an OK tradeoff, since the users can still see the example text, they just won't see a demo of it.

File: docs/src/pages/[platform]/components/authenticator/customization/customization.labels-and-text.web.mdx [hunk 2]
```diff
@@ -80,9 +80,5 @@ Using the same techniques as [Internationalization (I18n)](#internationalization
     });
     ```
 
-    <Example>
-      <LabelsAndTextDemo Component={Authenticator.SetupTOTP} />
-    </Example>
-
```
Comment (ErikCH) [inline docs/src/pages/[platform]/components/authenticator/customization/customization.labels-and-text.web.mdx:86]: Removed this example, see comment above.

**Review by joebuono — APPROVED** [review]
Thanks for doing this!

File: docs/src/pages/[platform]/components/authenticator/customization/LabelsAndTextDemo.tsx (hunk 1 above)
Comment (wlee221) [reply docs/src/pages/[platform]/components/authenticator/customization/LabelsAndTextDemo.tsx:74]: I like this, this example was very flimsy.

**Review by wlee221 — APPROVED** [review]
