### PR TITLE
fix(authenticator): Ensure setup has ran after refresh

### LINKED ISSUE #1623: React Authenticator Throws Error After Clicking Sign Up Tab
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App and Next

### Please describe your bug.

This bug occurs only after taking a few certain steps.

After these steps are taken clicking the 'Create Account' button will throw an error in the console and the user will not be able to continue on. These errors include:

Uncaught TypeError: Cannot read properties of undefined (reading 'length')
The above error occurred in the <n> component:

### What's the expected behaviour?

No errors should be shown

### Help us reproduce the bug!

1. Using the Authenticator log into an account. (Tested with email)
2. After logging in, refresh the browser page (make sure after logging in you see a logout button).
3. Click the log out button.
4. Click the 'Create Account' tab.

Error will be thrown. (This only occurs if you refresh the page after logging in, when you see the log out button)

### Code Snippet

```typescript

function App() {
  return (
    <div className="App">
      <Authenticator>
        {({ signOut }) => <button onClick={signOut}> Sign Out</button>}
      </Authenticator>
    </div>
  );
}

export default App;


```

### Additional information and screenshots

image

image
image

### LINKED ISSUE #1659: When login, refresh page, log out and then login again Authenticator crashes on formValues
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Authenticator

### How is your app built?

Create React App with react-app-wired to adjust webpack config

### Please describe your bug.

On login when pressing the 'Sign In' button it doesn't login and I can see the following error in the console logs (see attached screenshot)

This ONLY happens when you are logged in, refresh the page, log out and try to login again

### What's the expected behaviour?

That the user would be logged in normally without crashing

### Help us reproduce the bug!

- Open the application
- Login, which works as normal
- Refresh the page (F5)
- Log out
- Login again, but now the error is observed

### Code Snippet

```typescript
<Authenticator initialState="signIn" hideSignUp loginMechanisms={['email']}>
        {() => (
          <main>
            <AbilityContext.Provider value={currentAbilities}>
               .. Components ..
            </AbilityContext.Provider>
            <footer>
              <Footer />
            </footer>
          </main>
)}
</Authenticator>
```

### Additional information and screenshots

image

When looking at the code:
image

r.loginMechanisms is undefined in this situation while normally it contains ['email'] as defined in my authenticator.

### LINKED ISSUE #1676: User can't sign in after refresh
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
# Put output below this line
System:
    OS: Linux 5.15 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
    Memory: 1.58 GB / 15.50 GB
    Container: Yes
    Shell: 5.1.12 - /bin/bash
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
  Browsers:
    Chromium: 96.0.4664.110
    Firefox: 96.0
  npmPackages:
    @aws-amplify/ui-react: ^2.15.1 => 2.15.1 
    @aws-amplify/ui-react-internal:  undefined ()
    @aws-amplify/ui-react-legacy:  undefined ()
    @testing-library/jest-dom: ^5.16.4 => 5.16.4 
    @testing-library/react: ^12.1.4 => 12.1.4 
    @testing-library/user-event: ^13.5.0 => 13.5.0 
    aws-amplify: ^4.3.19 => 4.3.19 
    aws-amplify-react: ^5.1.9 => 5.1.9 
    react: ^18.0.0 => 18.0.0 (17.0.2, 16.14.0)
    react-dom: ^18.0.0 => 18.0.0 
    react-scripts: 5.0.0 => 5.0.0 
    web-vitals: ^2.1.4 => 2.1.4 
  npmGlobalPackages:
    @aws-amplify/cli: 8.0.0
    corepack: 0.10.0
    npm: 8.1.2
    react-native-cli: 2.0.1
    yarn: 1.22.17
```

</details>

### Describe the bug

When I use simple PoC with Amplify and withAuthenticator and when user wants to sign in there is an error:
Uncaught TypeError: r.loginMechanisms is undefined

A few weeks ago I created same simple PoC and everything worked fine (App.js file is in reproduction steps). Versions from few weeks ago (working version):
```
"react": "^17.0.2",                                                                                                                                           
"react-dom": "^17.0.2",
"@aws-amplify/ui-react": "^2.10.4",
"aws-amplify": "^4.3.17",
"aws-amplify-react": "^5.1.9"
```

### Expected behavior

I expect that user can sign in.

### Reproduction steps

npx create-react-app name-of-the-app
cd name-of-the-app
npm install aws-amplify @aws-amplify/ui-react aws-amplify-react --save-dev
modify src/App.js -> code is in Code Snippet section
npm run start
login with the user
refresh the page (without refresh everything works fine)
sign out the user
login with the user -> error

### Code Snippet

```js
// Put your code below this line.
import { useEffect } from 'react';
import { Amplify, Auth } from 'aws-amplify';
import { withAuthenticator } from '@aws-amplify/ui-react';
import '@aws-amplify/ui-react/styles.css';

Amplify.configure({
    Auth: {
        region: 'us-west-2',
        userPoolId: '',
        userPoolWebClientId: '',
    }
});


function App({signOut, user}) {
  return (
      <div>
        <h1>HI {user.username}</h1>
        <button onClick={signOut}>Sign out</button>
    </div>
  );
}

export default withAuthenticator(App, {
    variation: "default",
    signUpAttributes: ["email"]
});
```

### Log output

<details>

```
// Put your logs below this line
Uncaught TypeError: r.loginMechanisms is undefined
    formValues actions.js:1
    updatedContext utils.js:415
    updateContext utils.js:397
    resolveActions actions.js:420
    resolveTransition StateNode.js:887
    transition StateNode.js:828
    nextState interpreter.js:720
    provide serviceScope.js:8
    nextState interpreter.js:719
    send interpreter.js:104
    process scheduler.js:65
    schedule scheduler.js:44
    send interpreter.js:100
    sendTo interpreter.js:132
    exec interpreter.js:807
    execute interpreter.js:200
    update interpreter.js:226
    send interpreter.js:106
    process scheduler.js:65
    schedule scheduler.js:44
    send interpreter.js:100
    node_modules bundle.js:14539
    node_modules bundle.js:7993
    React 22
    js index.js:9
    factory react refresh:6
    Webpack 3
actions.js:1
```

</details>

### aws-exports.js

_No response_

### Manual configuration

```js
Amplify.configure({
    Auth: {
        region: 'us-west-2',
        userPoolId: '',
        userPoolWebClientId: '',
    }
});
```

### Additional configuration
```js
{
    "UserPool": {
        "Id": "",
        "Name": "FancyPool",
        "Policies": {
            "PasswordPolicy": {
                "MinimumLength": 8,
                "RequireUppercase": false,
                "RequireLowercase": false,
                "RequireNumbers": false,
                "RequireSymbols": false,
                "TemporaryPasswordValidityDays": 7
            }
        },
        "LambdaConfig": {
            "PreSignUp": "arn:aws:lambda:us-west-2:xxxx:function:socket_user_sign_up"
        },
        "LastModifiedDate": "2022-03-22T00:31:02.669000+01:00",
        "CreationDate": "2022-02-14T16:02:59.466000+01:00",
        "SchemaAttributes": [
            {
                "Name": "sub",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": false,
                "Required": true,
                "StringAttributeConstraints": {
                    "MinLength": "1",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "given_name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "family_name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "middle_name",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "nickname",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "preferred_username",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "profile",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "picture",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "website",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "email",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": true,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "email_verified",
                "AttributeDataType": "Boolean",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false
            },
            {
                "Name": "gender",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "birthdate",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "10",
                    "MaxLength": "10"
                }
            },
            {
                "Name": "zoneinfo",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "locale",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "phone_number",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "phone_number_verified",
                "AttributeDataType": "Boolean",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false
            },
            {
                "Name": "address",
                "AttributeDataType": "String",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "StringAttributeConstraints": {
                    "MinLength": "0",
                    "MaxLength": "2048"
                }
            },
            {
                "Name": "updated_at",
                "AttributeDataType": "Number",
                "DeveloperOnlyAttribute": false,
                "Mutable": true,
                "Required": false,
                "NumberAttributeConstraints": {
                    "MinValue": "0"
                }
            }
        ],
        "AutoVerifiedAttributes": [
            "email"
        ],
        "VerificationMessageTemplate": {
            "DefaultEmailOption": "CONFIRM_WITH_CODE"
        },
        "MfaConfiguration": "OFF",
        "EstimatedNumberOfUsers": 10,
        "EmailConfiguration": {
            "EmailSendingAccount": "COGNITO_DEFAULT"
        },
        "UserPoolTags": {},
        "Domain": "fancy-domain2022",
        "AdminCreateUserConfig": {
            "AllowAdminCreateUserOnly": false,
            "UnusedAccountValidityDays": 7
        },
        "UsernameConfiguration": {
            "CaseSensitive": false
        },
        "Arn": "arn:aws:cognito-idp:us-west-2:xxxx:userpool/xxxx",
        "AccountRecoverySetting": {
            "RecoveryMechanisms": [
                {
                    "Priority": 1,
                    "Name": "verified_email"
                }
            ]
        }
    }
}
```

### Mobile Device

_No response_

### Mobile Operating System

_No response_

### Mobile Browser

_No response_

### Mobile Browser Version

_No response_

### Additional information and screenshots

After npm run start I can see warnings related to missing files in node_modules/maplibre-gl-js-amplify/src/
I tried to do "npm install maplibre-gl-js-amplify" but that don't work.

### PR DESCRIPTION
**Pull request by wlee221**
#### Description of changes
This resolves issues when users try to sign in or sign up after they refresh in signed in state.

This happened because `setup` state was skipped when user has refreshed, and hence Authenticator would not send `INIT` event. This PR resolves it by ensuring setup has run after refresh + signing out.
 

#### Issue #, if available

Resolves #1623, Resolves #1676, Resolves #1659

#### Description of how you validated changes

Added new tests. Note how they fail on my first two commits but pass later after I add the fix.

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are updated
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/ui/src/machines/authenticator/index.ts [hunk 1]
```diff
@@ -170,7 +171,10 @@ export function createAuthenticatorMachine() {
             },
           },
           on: {
-            'done.invoke.signOutActor': 'signIn',
+            'done.invoke.signOutActor': [
+              { target: 'setup', cond: 'shouldSetup' },
+              { target: 'setup.goToInitialState' },
```
Comment (wlee221) [inline packages/ui/src/machines/authenticator/index.ts:176]: If we have already setup, we go to `setup.waitConfig` to get `INIT` event from Authenticator. Otherwise, we skip setup and go directly to `initialState`.

**Review by jacoblogan — APPROVED** [review]
LGTM

**Review by ErikCH — APPROVED** [review]
👍
