### PR TITLE
fix: add missing token for default font size for SwitchField

### LINKED ISSUE #2383: Default Switch Field Label Font Size Theme Token Missing
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have tried disabling all browser extensions or using a different browser
- [X] I have tried deleting the node_modules folder and reinstalling my dependencies
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

cra

### What browsers are you seeing the problem on?

Chrome

### Please describe your bug.

I'm not sure if this is a bug or as designed.

I noticed the switch field label in the default switch field size, doesn't have a theme token associated with it. This means it's inheriting font size from the document, which could potentially throw off the look and feel when compared to other label font sizes like for the text field.

Should there be a theme token for this, or is this intended?

### What's the expected behaviour?

I would have expected the default switch field to have a font size theme token like the TextField label component.

### Help us reproduce the bug!

Add the switch field to an app and don't use size property. The size of the label will be inherited from the page.

### Code Snippet

```typescript
// Put your code below this line.

<SwitchField label="This is a switch" />

```

### Additional information and screenshots

An example of how a switch field label can become very different than the surrounding labels.

Screen Shot 2022-08-01 at 2 09 47 PM

### PR DESCRIPTION
**Pull request by zchenwei**
#### Description of changes

Adding missing token for default font size for `SwitchField` so that it will not unpredictably inherit from any of its parent containers.

#### Issue #, if available

Fixes #2383 

#### Description of how you validated changes

Test locally on dev docs site

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are updated
- [x] No side effects or [`sideEffects`](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/CONTRIBUTING.md#code-standards) field updated

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by reesscot — APPROVED** [review]
LGTM

**Review by hbuchel — DISMISSED** [review]
lgtm, Thanks @zchenwei !

File: packages/ui/src/theme/tokens/components/switchField.ts [hunk 1]
```diff
@@ -92,6 +93,9 @@ export const switchfield: SwitchFieldTokens = {
   large: {
     fontSize: { value: '{fontSizes.large.value}' },
   },
+  medium: {
```
Comment (jacoblogan) [inline packages/ui/src/theme/tokens/components/switchField.ts:96]: I believe the pattern we use with the default (medium) size is to add the tokens directly onto the component instead of using a medium prefix.

Comment (zchenwei) [reply packages/ui/src/theme/tokens/components/switchField.ts:96]: Good catch, you are right

**Review by jacoblogan — APPROVED** [review]

**Review by ioanabrooks — APPROVED** [review]

**Review by wlee221 — APPROVED** [review]

**Review by reesscot — APPROVED** [review]
