### PR TITLE
fix(style): adjust color and border color on ToggleButton to meet 3:1 contrast ratio

### LINKED ISSUE #1825: Bug: ToggleButton "off" state text color does not meet WCAG AA min contrast ratio
### Before creating a new issue, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-ui/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-ui/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-ui/blob/main/CONTRIBUTING.md#bug-reports).

### On which framework/platform are you having an issue?

React

### Which UI component?

Other

### How is your app built?

Any

### Please describe your bug.

The toggle button in the "off" state does not meet WCAG AA color contrast requirements of 4.5:1

Screen Shot 2022-05-04 at 10 49 02 AM

Screen Shot 2022-05-04 at 10 35 02 AM
.

### What's the expected behaviour?

Color contrast should pass 4.5:1 criteria. I recommend we use the default Button text color. 

Screen Shot 2022-05-04 at 10 50 26 AM

Currently, the Toggle button looks like a disabled button (not interactive, readonly), but really it is in the "off" state.
 

### Help us reproduce the bug!

https://ui.docs.amplify.aws/components/togglebutton

### Code Snippet

```typescript
// Put your code below this line.

```

### Additional information and screenshots

_No response_

### PR DESCRIPTION
**Pull request by zchenwei**
#### Description of changes

1. Adjust text color on `ToggleButton` to meet 3 : 1 contrast ratio in both on/off state
2. Adjust border color to meet 3 : 1 contrast ratio in `on` state
3. Simply the `hover` styling a bit by removing `:not()` selector
4. Add 5px padding to demo container so box shadow will not get hidden

#### Issue #, if available

Fixes #1825

##### ToggleButton(on)
Screen Shot 2022-05-19 at 10 43 10 AM

###### Text color
Screen Shot 2022-05-18 at 4 48 41 PM

###### Border color
Screen Shot 2022-05-18 at 4 48 28 PM

##### ToggleButton(off)

Screen Shot 2022-05-19 at 10 42 34 AM

###### Text color
Screen Shot 2022-05-19 at 10 25 58 AM

###### Border color
Screen Shot 2022-05-19 at 10 26 10 AM

Dark mode

off
Screen Shot 2022-05-19 at 10 46 49 AM

on
Screen Shot 2022-05-19 at 10 48 32 AM

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are updated
- [x] No side effects or [`sideEffects`](https://github.com/aws-amplify/amplify-ui/blob/main/packages/react/CONTRIBUTING.md#code-standards) field updated

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/ui/src/theme/tokens/components/toggleButton.ts [hunk 1]
```diff
@@ -194,6 +195,7 @@ export const togglebutton: ToggleButtonTokens = {
       color: { value: '{colors.overlay.50.value}' },
     },
     _disabled: {
+      backgroundColor: { value: '{colors.transparent.value}' },
```
Comment (zchenwei) [inline packages/ui/src/theme/tokens/components/toggleButton.ts:198]: This is to override background from the default. It looks weird for a link to have a background. Also, I was wondering if we need a link variation for ToggleButton. It seems the use case is close to 0.

File: packages/ui/src/theme/tokens/components/toggleButton.ts [hunk 2]
```diff
@@ -155,14 +157,13 @@ export const togglebutton: ToggleButtonTokens = {
       borderColor: { value: '{colors.border.focus.value}' },
       backgroundColor: { value: '{colors.transparent.value}' },
       boxShadow: { value: '{components.fieldcontrol._focus.boxShadow.value}' },
-      color: { value: '{colors.overlay.50.value}' },
```
Comment (reesscot) [inline packages/ui/src/theme/tokens/components/toggleButton.ts:158]: Was this unused? Isn't it a breaking change to remove this?

File: packages/ui/src/theme/tokens/components/toggleButton.ts (hunk 1 above)
Comment (reesscot) [reply packages/ui/src/theme/tokens/components/toggleButton.ts:198]: Yeah, I can't think of a what a Link variation of a ToggleButton would be used for.

**Review by reesscot — COMMENTED** [review]
Looks good, just one one question before approving

File: packages/ui/src/theme/css/component/toggleButton.scss [hunk 3]
```diff
@@ -149,8 +154,9 @@
     --amplify-internal-togglebutton-primary-focus-border-color: var(
       --amplify-components-togglebutton-primary-focus-border-color
     );
+    //there is no primary focus color but this is being made and set to its default value so that it can be overwritten by the pressed primary focus color
```
[the remark this answers is not in the document]
Comment (zchenwei) [reply packages/ui/src/theme/css/component/toggleButton.scss:157]: I can split it manaully

File: packages/ui/src/theme/tokens/components/toggleButton.ts (hunk 2 above)
Comment (zchenwei) [reply packages/ui/src/theme/tokens/components/toggleButton.ts:158]: I think you are right. Even if this doesn't take any effects and inherit from default styling, I should keep it so that it is token customizable.

**Review by joebuono — APPROVED** [review]

**Review by 0618 — APPROVED** [review]

**Review by reesscot — APPROVED** [review]
shipit!
